# Stage 1: Build
FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR /app

# Copy toàn bộ source product-service
COPY ./product-service /app

# Build và package
RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy jar đã build
COPY --from=build /app/target/product-service-1.0.0-SNAPSHOT.jar ./product-service.jar

ENTRYPOINT ["java", "-jar", "product-service.jar"]
