# Stage 1: Build
FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR /app

# Copy toàn bộ source inventory-service
COPY ./inventory-service /app

# Build và package
RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy jar từ stage build
COPY --from=build /app/target/inventory-service-1.0.0-runner.jar ./inventory-service.jar

ENTRYPOINT ["java", "-jar", "inventory-service.jar"]
